### ISSUE TITLE
Noto Sans Tangsa font - issues for fixing

### ISSUE THREAD

**Issue by StephenMorey** [notofonts/tangsa#3]
I have been in contact with members of the Tangsa community in North East India who are using the Tangsa script created by late Lakhum Mossang that was approved for Unicode in 2021 and for which the Noto Sans Tangsa font has been made.

I have created a file, listing the issues that require some minor changes to the existing shapes of the letters in the Noto Sans Tangsa font, to make this font more usable
[Noto Font_Letters that need to be changed.pdf](https://github.com/notofonts/noto-fonts/files/9186344/Noto.Font_Letters.that.need.to.be.changed.pdf)

There are 8 letters that community members have suggested need to be altered. Each of these is discussed, as best I can, in the appended .pdf file.

**Comment by simoncozens** [comment]
Hi (again!) Stephen,

I have had a go at fixing these glyphs. I will take some advice from designers on the curve construction, but please see if these forms are more suitable to the community: (New at top, old at bottom)

<img width="654" alt="Screenshot 2022-10-17 at 12 05 23" src="https://user-images.githubusercontent.com/106728/196161853-e15d3dc7-4506-4cf1-b137-ebd6c86fe297.png">

**Comment by StephenMorey** [comment]
Dear Simon,

I hope this email does get to you, because I'm not sure it will. Do you have a test font for the font with the changes? This would allow me to send some longer documents to community members?

Stephen
________________________________

**Comment by StephenMorey** [comment]
Dear Simon,

Wanglung Mossang from the Tangsa community has written "Thank you sir, this stands absolutely beautiful and doesn't require any comment."

So, we can say the community members that I am in contact with are happy.

How can I access the revised Noto font so that I can make some documents in it?

Stephen
________________________________

**Comment by Davewillibobs** [comment]
Hello @StephenMorey,

I designed the typeface in question and would be more than happy to make changes to improve the font's readability and legibility.

Please drop me an email if you'd like me to contribute and we can discuss the next steps.

email: q45u5cpa8pyj@opayq.com

**Comment by simoncozens** [comment]
Thanks to @Davewillibobs, this was fixed in cef9072.
