### ISSUE TITLE
Version 1.504 lost some kerning pairs

### ISSUE THREAD

**Issue by dscorbett** [notofonts/tangsa#4]
### Font
NotoSansTangsa-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/tangsa/releases/tag/NotoSansTangsa-v1.504
Date: 2022-09-12

### Font version
Version 1.504

### Issue
Some kerning pairs were lost between versions 1.503 and 1.504. For example, <U+16AB9, U+16AC8> used to be kerned together by 40 units, but now they are not kerned. Was that intentional?

### Character data
𖪹𖫈
U+16AB9 TANGSA LETTER THA
U+16AC8 TANGSA DIGIT EIGHT

#### Version 1.504
![𖪹𖫈](https://user-images.githubusercontent.com/1124347/189671053-ea81409e-e89c-47a5-8382-24912745ed4e.png)
#### Version 1.503
![𖪹𖫈](https://user-images.githubusercontent.com/1124347/189671051-7288d07a-0462-413a-804e-b2230fc10785.png)

**Comment by simoncozens** [comment]
We swapped the kerning of pa and xa in #1, but we didn't update the kerning groups for other letters with the same right-hand shape. I've done that now.
