### ISSUE TITLE
What is the status of #3?

### ISSUE THREAD

**Issue by Mercury13** [notofonts/tangsa#6]
### Title 
#3 was seemingly fixed just partly. Some talks we didn’t hear?
Because of that, I don’t even know how complete Tangsa is and if there’s a reason to replace Lakhum (currently Unicode’s sample for Tangsa) with Noto.

### Font 
NotoSansTangsa-Regular.ttf

### Where the font came from, and when
Site: this repo, latest release
Date: 2023-06-22

### Font Version
1.505

### OS name and version
All OS

### Application name and version
All apps

### Issue
![image](https://github.com/notofonts/tangsa/assets/10164882/9592f58a-7c0a-4a64-afc6-13690c9e20ea)
Here’s your alpha fix done in #3 (TOP = ALPHA, BOTTOM = OLD). And you put some correspondence with Tangsa people that top is OK, but then in release 1.505…
1. 8E, done
2. 9E, seemingly done
3. A5, current version is something in between
4. 91, old version was taken
5. 9F, done
6. B4, done
7. A8, same as A5
8. AB, done

### Character data
U+16A91 Tangsa letter Long Uex
U+16AA5 Tangsa letter Ya
U+16AA8 Tangsa letter Nya
…
U+16AAA Tangsa letter Ba

### Screenshot
![image](https://github.com/notofonts/tangsa/assets/10164882/941e2e45-462a-466e-8d7d-9dde05ce1bdb)
![image](https://github.com/notofonts/tangsa/assets/10164882/b8e81c7c-c8b2-4500-8b3b-5c3ee3229aed)

**Comment by simoncozens** [comment]
I believe that #3 is fixed (which is why it is closed). David Williams produced new glyph shapes, and Stephen Morey confirmed them with the community; so as I understand it, the current forms are the preferred ones.

**Comment by Mercury13** [comment]
@simoncozens It was probably done behind our backs without any documentation visible to general public. I see that Morey confirmed BLACK SCREENSHOT, but Williams did SOMETHING IN BETWEEN.
