### ISSUE TITLE
Need to alter the shape of TANGSA LETTER FINAL NG (16A90) 

### ISSUE THREAD

**Issue by StephenMorey** [notofonts/tangsa#8]
I have been contacted by members of the Tangsa community, members of the Tangsa Script Development Committee in India, who are very pleased to have this font.
However, one issue has recently been raised relating to the shape of Tangsa Letter Final NG (16A90) which I have tried to explain in the document appended here.

In summary: In the existing Noto font, the two letters Tangsa Letter MA (16AAB) and Tangsa Letter Final NG (16A90) are very similar with a small straight line angled slightly upwards from the middle of the character on the left in Tangsa Letter Final NG (16A90) being the only difference.

According to community members, Tangsa Letter Final NG (16A90) needs to be altered in three ways. Firstly, rather than having a curve to the left in the middle of the vertical section of the character, it should be an angle. Secondly, if the angle is put into the character, there is no need for the straight line that emerges from the middle of the curve to it’s right. Thirdly, the loop at the bottom of the letter should not be the shape it is, but rather should cross over the bottom portion of the vertical section.

This is illustrated in the appended document. 

Thank you

[Tangsa Letter MA (16AAB) and Tangsa Letter Final NG (16A90).pdf](https://github.com/notofonts/tangsa/files/12533501/Tangsa.Letter.MA.16AAB.and.Tangsa.Letter.Final.NG.16A90.pdf)

**Comment by simoncozens** [comment]
Thanks so much for this! I'll ask Dave Williams if he would be interested in making a fix.

**Comment by simoncozens** [comment]
Thanks to David, this is now fixed! Interim builds are available from https://notofonts.github.io/tangsa/ but I'll do a formal release at the end of this month.

**Comment by StephenMorey** [comment]
I'm sorry to 'throw a spanner in the works' of a closed issue, but is it possible to find an image of the altered NG character or to find a font that has that new character in There are so many fonts on the link https://notofonts.github.io/tangsa/ and I did download one and installed it and it didn't have changed character. I want to be able to share this the amended shape with community members.

**Comment by simoncozens** [comment]
Old:
![old](https://github.com/notofonts/tangsa/assets/106728/5468a7e8-cdb0-439f-a5af-f7c3b309a125)

New:
![new](https://github.com/notofonts/tangsa/assets/106728/fdfbb086-f981-4c5c-b870-babeaa119751)

**Comment by StephenMorey** [comment]
Thank you

Is there are font including this that I can share with the community members to double check everything? Sorry to be difficult, but I just want to make sure that everything is covered.

Stephen
________________________________

**Comment by simoncozens** [comment]
This one should be correct: https://notofonts.github.io/tangsa/fonts/NotoSansTangsa/full/variable-ttf/NotoSansTangsa[wght].ttf

**Comment by StephenMorey** [comment]
Thank you
________________________________
